# BLOCKS
# A list of blocks that detect for fossils/artifacts

blocks:
  - GRASS_BLOCK
  - COBBLESTONE
  - STONE
  - ANDESITE
  - DIORITE
  - GRANITE
  - DIRT
  - COARSE_DIRT
  - GRAVEL

# WORLDS
# A list of worlds where you can find fossils/artifacts.

worlds:
  - world