name: Archaeology
main: com.ihusker.archaeology.Archaeology
version: ALPHA-3.0
api-version: 1.15
author: iHusker
softdepend: [Vault, Citizens]

commands:
  archaeology:
    description: The main command.
  redeem:
    description: Redeems an artifact.